name: github_search
description: Consumir a api do GitHub, seguindo os padrões de Clean Architercture proposta pela Flutterando.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dartz: ^0.9.1
  dio: ^3.0.9
  bloc: ^6.0.1
  rxdart: ^0.24.1
  flutter_modular: ^2.0.1
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
